name: CI/CD Pipeline for React-D3 App

on:
  push:
    branches:
      - main  # Runs only when code is pushed to main branch
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Lint Code
        run: npm run lint || echo "Linting Failed but Continuing"

      - name: Build Project
        run: npm run build

      - name: Deploy to GitHub Pages (Optional)
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Vite outputs build files to 'dist'
